import type { WorkflowStepDefinition } from "@/lib/workflow-contract";

export const workflowStepDefinitions: WorkflowStepDefinition[] = [
  {
    id: "reset",
    title: "Reset target",
    owner: "Tool Runtime",
    kind: "tool",
    dependsOn: [],
    description: "Restores the controlled mobile checkout bug before investigation.",
  },
  {
    id: "triage",
    title: "Triage customer report",
    owner: "Triage Agent",
    kind: "agent",
    dependsOn: ["reset"],
    agentId: "triage",
    description: "Extracts severity, affected environment, and expected behavior.",
  },
  {
    id: "vision",
    title: "Inspect visual evidence",
    owner: "Vision Agent",
    kind: "agent",
    dependsOn: ["triage"],
    agentId: "vision",
    description: "Reads the mobile screenshot and checks the missing CTA region. Processed via Venice.ai TEE - customer screenshot data never leaves the encrypted enclave.",
  },
  {
    id: "log",
    title: "Correlate client events",
    owner: "Log Agent",
    kind: "agent",
    dependsOn: ["triage"],
    agentId: "log",
    description: "Orders checkout telemetry around coupon and payment state.",
  },
  {
    id: "repro",
    title: "Drive browser repro",
    owner: "Repro Agent",
    kind: "tool",
    dependsOn: ["vision", "log"],
    agentId: "repro",
    description: "Uses Playwright to open the mobile target, apply SAVE20, and assert CTA visibility.",
  },
  {
    id: "bug-report",
    title: "Write bug report",
    owner: "Code Agent",
    kind: "summary",
    dependsOn: ["repro"],
    agentId: "code",
    description: "Turns confirmed evidence into an engineering issue artifact.",
  },
  {
    id: "code",
    title: "Localize source",
    owner: "Code Agent",
    kind: "agent",
    dependsOn: ["bug-report"],
    agentId: "code",
    description: "Finds the likely component and breakpoint-dependent defect.",
  },
  {
    id: "patch-plan",
    title: "Plan constrained patch",
    owner: "Patch Runtime",
    kind: "patch",
    dependsOn: ["code"],
    description: "Asks the model for rationale while keeping the patch allowlisted.",
  },
  {
    id: "patch-verify",
    title: "Apply and verify patch",
    owner: "Patch Runtime",
    kind: "patch",
    dependsOn: ["patch-plan"],
    description: "Applies the allowlisted change and reruns desktop/mobile Playwright verification.",
  },
  {
    id: "repo-pr",
    title: "Open GitHub issue and PR",
    owner: "GitHub Runtime",
    kind: "tool",
    dependsOn: ["patch-verify"],
    description: "Creates or reuses the issue, pushes a fix branch, and opens the PR in divagr18/mobile-demo.",
  },
  {
    id: "maintainer",
    title: "Prepare handoff",
    owner: "Maintainer Agent",
    kind: "agent",
    dependsOn: ["repo-pr"],
    agentId: "maintainer",
    description: "Drafts the final maintainer summary after verification passes.",
  },
];
